# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Portfolio Objective Function
#'
#' Calculates the objective function for portfolio optimization.
#' The objective is to maximize mean return while minimizing risk.
#'
#' @param weights Vector of portfolio weights
#' @param returns Matrix of asset returns (rows = time, cols = assets)
#' @param cov_matrix Covariance matrix of asset returns
#' @param risk_aversion Risk aversion parameter (default: 0.5)
#' @return Objective function value (negative for maximization)
#'
portfolio_objective <- function(weights, returns, cov_matrix, risk_aversion = 0.5) {
    .Call(`_PortfolioOptimizer_portfolio_objective`, weights, returns, cov_matrix, risk_aversion)
}

deoptim_portfolio_rcpp <- function(returns, cov_matrix, min_weight = 0.01, max_weight = 0.15, pop_size = 50L, max_iter = 200L, F = 0.8, CR = 0.9, ncores = 1L, DEBUG = FALSE) {
    .Call(`_PortfolioOptimizer_deoptim_portfolio_rcpp`, returns, cov_matrix, min_weight, max_weight, pop_size, max_iter, F, CR, ncores, DEBUG)
}

#' Create Equal-Weight Portfolio
#'
#' Creates an equal-weight portfolio with weights summing to 1.
#'
#' @param n_assets Number of assets in the portfolio
#' @return Vector of equal weights
#'
equal_weight_portfolio <- function(n_assets) {
    .Call(`_PortfolioOptimizer_equal_weight_portfolio`, n_assets)
}

#' Calculate Portfolio Returns
#'
#' Calculates the returns of a portfolio given weights and asset returns.
#'
#' @param returns Matrix of asset returns (rows = time, cols = assets)
#' @param weights Vector of portfolio weights
#' @return Vector of portfolio returns
#'
portfolio_returns <- function(returns, weights) {
    .Call(`_PortfolioOptimizer_portfolio_returns`, returns, weights)
}

#' Calculate Sharpe Ratio
#'
#' Calculates the Sharpe ratio of a portfolio.
#'
#' @param returns Vector of portfolio returns
#' @param risk_free Risk-free rate (default: 0)
#' @return Sharpe ratio
#'
sharpe_ratio <- function(returns, risk_free = 0.0) {
    .Call(`_PortfolioOptimizer_sharpe_ratio`, returns, risk_free)
}

